### PR TITLE
Gate node attribute `scratchpad_state` behind features for sway compat

### PR DESCRIPTION
**Pull request by sophacles**
Re: #45

### CODE REVIEW

**Comment by leshow** [comment]
Are there other fields that need the gate or is this it?

**Comment by leshow** [comment]
In any case, I'll merge this now.

**Comment by sophacles** [comment]
Hi @leshow Sorry about the radio silence on this, some work stuff started demanding my attention pretty hard. I didn't find other things directly  - although there are a couple commands and structs (for outputs/displays) in sway that I'll add at some point in a different PR.

**Comment by leshow** [comment]
No worries, the notifications sometimes don't get to me anyway so feel free to ping me directly with `@`. Thanks

**Pull request merged**
