### PR TITLE
Node: add layout field

### PR DESCRIPTION
**Pull request by chmln**
Per https://i3wm.org/docs/ipc.html#_tree_reply

### CODE REVIEW

**Comment by leshow** [comment]
Thank you!

**Comment by leshow** [comment]
While I have you here, can I ask. Does this cause an error? I haven't noticed any serialization errors. If it does, we'll probably want to increment the version of `i3ipc-types` and it's dependent crates

**Comment by chmln** [comment]
@leshow I don't foresee anything breaking since we just added a field that was omitted. There were, of course, no errors reported by cargo check.

**Comment by chmln** [comment]
Also, thank you for making this - `tokio-i3ipc` has been a pleasure to use. I'm using the library to implement automatic tiling for i3 (https://github.com/chmln/i3-auto-layout)

**Comment by leshow** [comment]
Thanks! I scoped out your project after you submitted the PR. Looks cool! If you find anything else be sure to let me know. Sidenote, we're in the same city! Take care

**Pull request merged**
