### PR TITLE
Improve Travis CI

### LINKED ISSUE #12: Make CI better
Would be nice to have a CI that runs  rustfmt, clippy, cargo doc, and cargo test

### PR DESCRIPTION
**Pull request by PurpleMyst**
This should add what's requested to the travis CI build. The build is currently not passing due to some unused imports, however.

Resolves #12

### CODE REVIEW

**Comment by leshow** [comment]
This is a bit of a weird error, I'm able to build all of these crates with `cargo build`, but both rust-analyzer in vscode and clippy seem to have a problem with picking up the right imports.

**Comment by PurpleMyst** [comment]
Could this be a feature problem?

**Comment by PurpleMyst** [comment]
What is this code supposed to do? No `UnixStream` I know of has an `_encode_msg` method

https://github.com/leshow/tokio-i3ipc/blob/ead6856d3ab9de3c0c6d14671e3015a97dab9c88/async-i3ipc/src/lib.rs#L93-L109

**Comment by leshow** [comment]
There's a blanket impl in i3ipc-types, https://github.com/leshow/tokio-i3ipc/blob/master/i3ipc-types/src/lib.rs#L103
```
// Any type which brings `I3IPC` into scope and implements Read and Write gets
// the protocol implemented for free
impl<T: io::Read + io::Write + I3Protocol> I3IPC for T {}

#[cfg(all(not(feature = "async-traits"), not(feature = "async-std-traits")))]
impl<T: io::Read + io::Write> I3Protocol for T {}
```
if you impl `Read` and `Write` you get the `I3Protocol` methods implemented, and if you have all of those you get the `I3IPC` (which contains the decode method, only useful for std traits).

Looking at this section, it could use a little refactor, it was added to in a bit ad-hoc way. However, I don't understand why clippy would throw an error, it very clearly only is implemented if you don't use the async traits

**Comment by leshow** [comment]
Ah! I think I know. I've got everything in a single cargo workspace, but the flags for the dependencies are mutually exclusive. If a workspace builds a single Cargo.lock file, then I could see why it would error out on those lines when built together but succeed when built individually

**Comment by leshow** [comment]
Okay I've all but confirmed the above is the case, I've got another PR that "fixes" this by remove the workspace. It means each cargo fmt/clippy/test will be need to run individually on each of the subdirs, but I think that's okay.

Lesson learned, a you can't have mutually exclusive features for a local dependency inside a workspace!

**Comment by PurpleMyst** [comment]
Do you want me to fix the CI to work like that? Also, it's reccommended that features work additively because of this reason, but I don't see a way to do that here. For the future, maybe it could be a good idea to introduce a compiler error if both features are enabled? (via `#[cfg(...)` and `compile_error!`)

**Comment by leshow** [comment]
Sure, I'm going to merge the re-org, if you want to rebase or merge and make the CI changes again that would be great. `compile_error!` is a good idea too, if not just a refactor.

**Pull request merged**
